// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/jinzhu/gorm"
	"torimo-article-api/src/handler"
	"torimo-article-api/src/infrastructure/db/store"
	"torimo-article-api/src/interactor"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func Initialize(d *gorm.DB) *handler.ArticleHandler {
	iArticleRepository := store.NewArticleDatastore(d)
	iArticleUsecase := interactor.NewArticleInteractor(iArticleRepository)
	articleHandler := handler.NewArticleHandler(iArticleUsecase)
	return articleHandler
}
